import Auth from "./Auth";
import Home from "./Home";
import Events from "./Events";
import Maps from "./Maps";
import News from "./News";
import Notes from "./Notes";
import SubjectNotes from "./SubjectNotes";
import Quiz from "./Quiz";
import Admin from "./Admin";
export { Auth, Home, Events, Maps, News, Notes, SubjectNotes, Quiz, Admin };
